name: Development build

on:
  [push, workflow_dispatch]

jobs:
  build:
    name: Development build
    runs-on: dore-dingusvm
    steps:
      - name: Set up build environment pt. I
        uses: actions/checkout@v2

      - name: Set up build environment pt. II
        run: git submodule update --init --recursive
        
      - name: Build the Debian package
        run: gmake -j$(sysctl -n hw.ncpu) dsym

      - name: Upload regular artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.development_iphoneos-arm.deb
          path: artifacts/net.kdt.pojavlauncher.*_iphoneos-arm.deb
          
      - name: Upload rootless artifact
        uses: actions/upload-artifact@v2
        with:
          name: net.kdt.pojavlauncher.development-rootless_iphoneos-arm.deb
          path: artifacts/net.kdt.pojavlauncher.*_iphoneos-arm64.deb

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
